fixed the disable and enable button position
openstreetmap/iD pull request #10556
Opened 2024-11-25 15:51 UTC by draunger

2024-12-09 20:10 UTC, draunger commented
@bhousel can you review my PR and if you seems it has some issue please tell me regarding this

2024-12-09 20:51 UTC, bhousel commented
> @bhousel can you review my PR and if you seems it has some issue please tell me regarding this

Using absolute positioning and a -532px margin is certainly one way to move the text, but it's not how I would do it.  
What if later someone wants to change the checkboxes or the font or something.

<img width="754" alt="Screenshot 2024-12-09 at 3 47 50 PM" src="https://github.com/user-attachments/assets/5be69919-3bfb-4e26-b432-028531826719">

2024-12-10 16:11 UTC, draunger commented
@bhousel ok i understand then please give me some time i can change my approach

2024-12-10 16:48 UTC, bhousel commented
> @bhousel ok i understand then please give me some time i can change my approach
> but sir one question , without applying css how we can change the position of the buttons

insert them into the document where you want them to be

2024-12-12 14:19 UTC, draunger commented
hey @bhousel i have changed the position of the footer without css but now it look like this but in this image map feature text and both button i.e(disable all and enable all) are not aligning in the same line.
![image](https://github.com/user-attachments/assets/eafa7c47-12f5-428c-aa0a-44208d815f65)
if i use absolute property in map feature text css then it looks like this :
means i have apply css on the text of map feature not on the buttons :
so which i use above or this ??
![image](https://github.com/user-attachments/assets/9c5d8dfe-4352-4f09-9c41-683a20a9577c)

2024-12-22 13:08 UTC, draunger commented
hey @bhousel what do you think which method i use as stated above ?

2025-01-14 11:39 UTC, k-yle requested changes
Hi @draunger, as Bryan mentioned, using a margin of `-532px` isn't a particularly robust solution. It also has consqeuences for other components that use the same class name.

It would be more idiomatic to move `div.feature-list-links` above `ul.layer-feature-list`. You can find the relevant code here:

https://github.com/openstreetmap/iD/blob/ff8f044994ef418b614dd18f73c3e81e2946b381/modules/ui/sections/map_features.js#L27-L29

2025-01-25 18:14 UTC, draunger commented
@k-yle ok sending its PR

2025-02-11 17:29 UTC, draunger commented
@k-yle i have made the changes as you said , you can now review it :)

2025-02-13 16:03 UTC, draunger commented
@tyrasd in this PR i have changed the "disable all" and "enable all" buttons position as you can see in this:
![image](https://github.com/user-attachments/assets/af71dc6f-b6f3-4a61-9458-535b01c7589b)

2025-08-07 11:42 UTC, tyrasd commented
closing in favor of #11268

2025-08-07 11:42 UTC, closed without merging