Fix visible grid around tiles
openstreetmap/iD pull request #10594
Opened 2024-12-11 02:19 UTC by Nekzuris

This properly fixes #10589 by removing the tile overlap that was causing white borders with transparent tiles.

The tile overlap was added as a dirty fix to #3053, it doesn't even fully resolved the issue anyway.
My fix uses the CSS rule `mix-blend-mode: plus-lighter`, applied only to the background layer and is only really needed for Chrome.
A future version of Chrome might make this CSS rule unnecessary, but leaving it shouldn't cause the borders to reappear.

Tested on Chrome and Firefox with normal and fractional zoom levels, with regular and transparent layers.
Not tested on macOS Safari or mobile.

2024-12-11 12:57 UTC, tyrasd requested changes, later dismissed
Hmm… Nice idea, but there are still corner cases where it does not work: To reproduce on Chrome 129 on Ubuntu, set browser zoom to 110%:

![image](https://github.com/user-attachments/assets/bb1342fd-d1a0-44a8-835d-7892386ddd58)

And, more importantly, now even non-transparent tile layers show the seam under the above mentioned conditions (this works fine on the development branch):

![image](https://github.com/user-attachments/assets/2d7799f9-fd37-4d34-90ef-3d2a888c5938)

<hr>

I think the +epsilon workaround is still needed to account for rounding errors associated with fractional browser zoom settings.

To improve the rendering of the small overlap for tile layers with transparency, I tried to play around with a few other combinations of CSS blend modes, background values, etc. but could unfortunately not find a solution that preserves the rendering of the non transparent tiles. :unamused: 

As transparent imagery layers are a rather rare occurence[^1], I'm leaning towards closing this as an unfortunate _wontfix / known bug_. Except if you or someone is able to find a better solution?!

[^1]: some overlays use an alpha channel, but as long as it is only used as a mask ("1 bit transparency"), these also work fine with the current solution.

2024-12-11 20:32 UTC, Nekzuris commented
It is unfortunate that it doesn't work for 110% zoom in Chrome but it's fine with 125%, 150%, 175%, 200%.

The current solution with +epsilon to scale up by 1px and create an overlap is fundamentally flawed because it messes with tiles sharpness and will never work for transparent layers.
It's also only needed to fix a rendering bug in Chrome and doesn't even completely fix the issue at regular zoom levels and 100% browser zoom: https://www.openstreetmap.org/edit#map=16/48.36450/7.14242&background=MAPNIK
![image](https://github.com/user-attachments/assets/31a7f024-27f0-4e4a-98c0-94661a1ec82f)

Value 90% and 80% are also problematic with both epsilon or plus-lighter, but 75% is fine.
So with my testing, the +epsilon only improves the situation for 110% in Chrome.
While removing it in favor of plus-lighter :
- fixes everything at 100%
- makes perfect zooming transitions
- supports transparent layers
- but slightly degrades experience at 110% in Chrome

The solution `mix-blend-mode: plus-lighter` was also considered the best by [Leaflet#8891](https://github.com/Leaflet/Leaflet/pull/8891)

I found that not applying plus-lighter at 110% improves the situation, as well as 80% and 67%.
90% is still bad in Chrome and might be improved with specific epsilon value in JS, but I don't think that's a good idea.

2024-12-12 21:00 UTC, Nekzuris commented
I tried to compile in a comprehensive way everything I've tested to remove the grid:
`0.002 normal` is the current solution
`0 plus-lighter` is the Leaflet solution
`0 normal` is an exception (only included if it's an improvement)

### Firefox
| Browser zoom | epsilon | mix-blend-mode | normal zoom | fractional zoom | zoom transition | transparent layer |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| any | 0.002 | normal | ✔️ | ✔️ | ❌ | ❌ |
| any | 0 | normal or plus-lighter | ✔️ | ✔️ | ✔️ | ✔️ |

### Chrome
<table><thead>
  <tr>
    <th>Browser zoom</th>
    <th>epsilon</th>
    <th>mix-blend-mode</th>
    <th>normal zoom</th>
    <th>fractional zoom</th>
    <th>zoom transition</th>
    <th>transparent layer</th>
  </tr></thead>
<tbody>
  <tr>
    <td rowspan="3">50%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.006</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
  </tr>
  <tr>
    <td rowspan="3">67%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>✔️</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.003</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter or normal *</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td rowspan="3">75%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.004</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
  </tr>
  <tr>
    <td rowspan="4">80%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.003</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>〰️</td>
  </tr>
  <tr>
    <td rowspan="3">90%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.005</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter or normal</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td rowspan="3">100%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.003</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
  </tr>
  <tr>
    <td rowspan="3">110%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>〰️</td>
  </tr>
  <tr>
    <td rowspan="3">125%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>〰️</td>
    <td>〰️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0.003</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
  </tr>
  <tr>
    <td rowspan="2">150-400%</td>
    <td>0.002</td>
    <td>normal</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>0</td>
    <td>plus-lighter</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
    <td>✔️</td>
  </tr>
</tbody></table>
* normal is a bit better 
〰️ means okayish

#
TLDR: This PR with 3 CSS exceptions is a clear improvement over the current solution, the only minor regression is 110% in Chrome. We could go further with more logic in JS to keep epsilon in some cases but I don't like it.

2024-12-12 21:19 UTC, Nekzuris commented
I tried to compile in a comprehensive way everything I've tested to remove the grid:
`0.002 normal` is the current solution
`0 plus-lighter` is the Leaflet solution
`0 normal` is an exception (only included if plus-lighter isn't perfect)

### Firefox
| Browser zoom | epsilon | mix-blend-mode | normal zoom | fractional zoom | zoom transition | transparent layer |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| any | 0.002 | normal | ✔️ | ✔️ | ❌ | ❌ |
| any | 0 | normal or plus-lighter | ✔️ | ✔️ | ✔️ | ✔️ |

### Chrome
![image](https://github.com/user-attachments/assets/8a30203c-c610-4d25-a0a0-52ca9114fd01)

\* normal is a bit better 〰️ means okayish
(image because the html table broke the markdown, message wouldn't send)

#
TLDR: This PR with 3 CSS exceptions is a clear improvement over the current solution, the only annoying regression is 110% in Chrome but it's minor. We could go further with more logic in JS to keep epsilon in some cases but I don't like it.

2024-12-13 02:24 UTC, Nekzuris commented
### Visual before vs after

current zoom 100%

https://github.com/user-attachments/assets/ee6b6985-19d1-4dca-bf47-b5e3b0cef19f

new zoom 100%

https://github.com/user-attachments/assets/38562223-9b32-47af-bd0d-cc8d01687640

current zoom 110%

https://github.com/user-attachments/assets/932d8c99-e981-4dbf-a02c-1dfdf4e294e5

new zoom 110%

https://github.com/user-attachments/assets/85e079e1-ee51-4210-b871-9f71e907cf38

I chose Carto because it's where the grid is most noticeable.

### Here is what it looks like with real imagery at zoom 18

current vs new 100%
<img src="https://github.com/user-attachments/assets/878fdad5-8817-49de-8238-c2ac39c099e0" width="50%" title="current 100%"><img src="https://github.com/user-attachments/assets/fe84430c-80a7-4900-80b3-375a3a0f720d" width="50%" title="new 100%">
(click for full resolution)

current vs new 110%
<img src="https://github.com/user-attachments/assets/33984348-82d3-4b60-abf3-c27ecfa73b10" width="50%" title="current 110%"><img src="https://github.com/user-attachments/assets/b2184600-3504-4a8e-868b-45dcdd3f4bef" width="50%" title="new 110%">
The thin black lines currently visible at 100% are now at 110%.

I think most users will only really notice and appreciate the new flawless zoom transition.

2024-12-13 14:39 UTC, tyrasd commented
Thanks for the in-depth analysis and detailed tests!

> The current solution with +epsilon to scale up by 1px and create an overlap is fundamentally flawed because it messes with tiles sharpness and will never work for transparent layers.

Good point about the loss in sharpness with the existing workaround. I'm tending towards accepting the `0 plus-lighter` implementation, but what do you think about using a dynamic epsilon? That is only set to a non-zero value when the workaround is really "needed": i.e. Chromium-based browser and `window.devicePixelRatio` is one of the "problematic" values.

2024-12-13 18:49 UTC, Nekzuris commented
I did my initial test with all the logic in the `tileSizeAtZoom` function, but it had a noticeable performance impact. I thought this function was only called for rendering tiles, but it's called hundreds of times even when the data layer is hidden, not sure if that's normal.

This is a better implementation, but maybe you have an even better idea.
And unlike the exceptions in CSS, this will still prevent good zooming transitions and transparent layers when the [chromium bug](https://issues.chromium.org/issues/40084005) is fixed.

2024-12-13 18:56 UTC, Nekzuris commented
Is the failed test caused by the EventListener ?

2024-12-15 00:10 UTC, Nekzuris commented
While testing for Leaflet [here](https://github.com/Leaflet/Leaflet/pull/9560#issuecomment-2543372689), I found that _plus-lighter_ can introduce some blur on Chrome, but it's nothing to worry about because iD is already blurry all the time due to sub-pixel translations.
Sub-pixel precision is apparently needed (see #2849), and trying to fix it for the map would create a noticeable sharpness difference when switching between normal and fractional zoom levels.

Again, this is only an issue on Chrome, Firefox handles both sub-pixel translations and plus-lighter just fine.

2024-12-17 06:05 UTC, Nekzuris commented
After further testing with non-standard pixel ratios, I found that the _plus-lighter_ trick only works with zoom levels that are multiples of 25 (75%, 100%, 125%...).

So instead of a few exceptions, I changed it to be applied only at those specific pixel ratios where it’s been confirmed to work well.
And for all the other case we still use the dynamic epsilon with 0.003 by default.

2024-12-18 05:40 UTC, tordans commented
Just to put this out there: We could also decide to not support zoomed in UIs and leave it at that. 
Or, consider adding a notice for zoomed in UIs for those users that zoom in but forgot about it.
TBH I am not sure it the added complexity of the workarounds and their added maintenance burden are worth it compared to the issue and how many users are likely affected (not many).

2024-12-18 06:41 UTC, Nekzuris commented
I originally made this PR to support transparent tiles and improve zoom transitions (which are currently awful for everyone), and fix the thin black lines visible with light backgrounds on Chrome.

The situation seems complex due to all the incremental improvements, but I think the final solution isn't that hard to understand.

If you ignore all other pixel ratios, simply remove _epsilon_ and apply _plus-lighter_ with no condition. That would improve things for the majority, but it would certainly be a regression for some.

There are many valid reasons to not have your zoom set to 100%, especially with high DPI screens, which are much more common now.

This mess is entirely caused by poor rendering in Chrome, and the only maintenance I foresee is removing all this when the [bug](https://issues.chromium.org/issues/40084005) is fixed.

2024-12-18 14:20 UTC, tyrasd approved these changes
Thanks again! This seems to be the best we can do for now.

Below, I've added a few inline links to this PR for future reference.

2024-12-18 14:20 UTC, tyrasd commented on css/80_app.css
> +/* Should be removed when https://issues.chromium.org/issues/40084005 is resolved */
```suggestion
/* Workaround to remove visible grid around tile borders on Chrome
   Only works with browser zoom multiple of 25 (75%, 100%, 125%...) 
   Should be removed when https://issues.chromium.org/issues/40084005 is resolved.
   See https://github.com/openstreetmap/iD/pull/10594 */
```

2024-12-18 14:20 UTC, tyrasd commented on modules/renderer/tile_layer.js
> +    // Should be removed when https://issues.chromium.org/issues/40084005 is resolved
```suggestion
    // Should be removed when https://issues.chromium.org/issues/40084005 is resolved
    // See https://github.com/openstreetmap/iD/pull/10594
```

2024-12-18 14:31 UTC, merged