Add some build tips encountered on Raspberry Pi.
openstreetmap/iD pull request #7651
Opened 2020-06-03 13:31 UTC by jleedev

2023-09-24 21:11 UTC, pnorman requested changes

2023-09-24 21:11 UTC, pnorman commented on CONTRIBUTING.md
> +installation but running the tests on a Raspberry Pi has not been attempted.)
I don't think specific hardware should be mentioned in the documentation.

2023-09-24 21:11 UTC, pnorman commented on CONTRIBUTING.md
> +Then you should do exactly that, such as `apt install phantomjs`.
If https://github.com/openstreetmap/id#prerequisites is outdated, it should be updated

2023-09-24 21:11 UTC, pnorman commented on CONTRIBUTING.md
> +qt.qpa.screen: QXcbConnection: Could not connect to display".**
What OS did you encounter this on? This looks like a bad phantomjs install, not an iD issue

2023-09-25 01:33 UTC, jleedev commented
Most of this has suffered from bit rot, as phantomjs isn't even being used anymore, so I'll close this.

Just some notes:

- https://github.com/openstreetmap/id#prerequisites doesn't say anything about dependencies, but https://github.com/openstreetmap/iD/blob/develop/CONTRIBUTING.md#tests says that karma needs CHROME_BIN pointing at the path to chromium, which seems good.
- The phantomjs install really was that flaky, _and_ would leave the node_modules in a broken state that `npm install` didn't fix.
- The low memory situation is still valid, but not really worth mentioning. (But wow, Karma manages to consume 1.5G of memory just to tell me that it can't find Chrome.)

2023-09-25 01:33 UTC, closed without merging