Update defibrillator preset
openstreetmap/iD pull request #7925
Opened 2020-08-24 19:26 UTC by nlehuby

2020-09-02 21:06 UTC, quincylvania commented on data/presets/fields/defibrillator_location.json
> +{
We usually use subdirectories for tags with colons. Could you move/rename this file to `fields/defibrillator/location.json`?

2020-09-02 21:06 UTC, quincylvania commented on data/presets/fields/defibrillator_location.json
> +    "label": "Precise location of the defibrillator"
Can we change the name to something shorter like "Location Description"?

2020-09-02 21:07 UTC, quincylvania requested changes
Looks fine, just a couple details I noticed.

2020-09-03 07:08 UTC, nlehuby commented
Thanks for you review.

2020-09-03 12:41 UTC, quincylvania approved these changes

2020-09-03 12:41 UTC, merged

2020-09-03 12:43 UTC, quincylvania commented
@nlehuby Thanks for your contribution!