added morgue preset
openstreetmap/iD pull request #8038
Opened 2020-09-30 22:33 UTC by animesh-007

Fixes #7958 
Added morgue preset.

2020-10-02 19:11 UTC, quincylvania requested changes

2020-10-02 19:11 UTC, quincylvania commented on data/presets/presets/morgue.json
> +        "amenity": "morgue"
The tag for this is still `amenity=mortuary` even though I requested the label be "Morgue".

2020-10-03 18:37 UTC, animesh-007 commented
@quincylvania I have made suggested changes can you look at once and let me know if you want me to change the "name" to "Mortuary" also.

2020-10-05 14:23 UTC, merged

2020-10-05 14:28 UTC, quincylvania commented
@animesh-007 Thanks!