Introduce issue templates
openstreetmap/iD pull request #8746
Opened 2021-10-10 18:48 UTC by tordans

This is a take to solve https://github.com/openstreetmap/iD/issues/8723.

Test: https://github.com/tordans/iD/issues/new/choose

It introduces …

- one template for bugs - example https://github.com/tordans/iD/issues/1
- one template for features/ideas – example https://github.com/tordans/iD/issues/2
- and most importantly one link to the id-tagging-schema repo, so there is a better chance that issues get created in the correct repository

There is still a link on the `/choose` page to create a blank issue.

## Docs

- About setting up the link to an external URL, which is used for the id-tagging-schema repo in this case https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
- Syntax for issue forms https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
- Syntax for GitHub's form schema https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
- Its important to understand, that this PR uses the `.yaml` version of issue templates, which allows to configure a form. Most resources online talk about the `.md` version, which allow to pre fill the form with markdown.

2021-10-21 10:53 UTC, mbrzakovic requested changes

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_bug.yaml
> +description: You found and issue with iD Editor on openstreetmap.org/edit.
```suggestion
description: You found an issue with iD Editor on openstreetmap.org/edit.
```

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_bug.yaml
> +      description: Please add screenshots that helps understand you issue.
```suggestion
      description: Please add screenshots or additional information to help us understand your issue.
```

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_bug.yaml
> +        - Other
```suggestion
```

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_feature.yaml
> +      description: Please add screenshots if they help understand you request/idea/question.
```suggestion
      description: Please add screenshots if they can help us understand your request/idea/question.
```

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_feature.yaml
> +    id: url
I think that sometimes less is more. I recommend we drop the URL section in Feature/Idea/Question

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/config.yml
> +  - name: There is an issue with a preset or tagging recommendation
```suggestion
  - name: There is an issue with presets or osm tagging recommendations
```

2021-10-21 10:53 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please share your feedback in the id-tagging-schema repository.
Lets also add name suggestion index.
Name can be: There is an issue with brands or brand icons.
Link: https://github.com/osmlab/name-suggestion-index
About: Please create a feature request in the name-suggestion-index repository.

2021-10-21 10:54 UTC, mbrzakovic commented on .github/ISSUE_TEMPLATE/id_editor_bug.yaml
> +      label: What browsers are you seeing the problem on?
```suggestion
      label: Which browsers are you seeing this problem on?
```

2021-10-21 12:32 UTC, tordans commented
@mbrzakovic thanks for looking into this!

I applied you suggestions. Lets Squash-Merge this once it is ready (or I can squash manually, if you prefer).

2021-10-21 13:04 UTC, mbrzakovic commented
> @mbrzakovic thanks for looking into this!
> 
> I applied you suggestions. Lets Squash-Merge this once it is ready (or I can squash manually, if you prefer).

Great! Can you please merge this change to your main branch in https://github.com/tordans/iD.
I'd like to give one last look to how the templates will look like.

2021-10-22 10:07 UTC, tordans commented
> … Can you please merge this change to your main branch in https://github.com/tordans/iD. I'd like to give one last look to how the templates will look like.

@mbrzakovic done – https://github.com/tordans/iD/issues/new/choose

I also squashed the commits for this PR.

2021-10-22 10:08 UTC, tordans commented
FYI, I just found another typo and changed it in https://github.com/openstreetmap/iD/pull/8746/commits/b378f6a17f62bba19789e89c6d472403e3dc69c4

2021-10-25 12:47 UTC, mbrzakovic approved these changes

2021-10-25 12:47 UTC, merged