clear labels for OSM hyperlinks in history panel (OSM history & OSM Profile)
openstreetmap/iD pull request #8834
Opened 2021-12-01 16:54 UTC by jasonghent98

Hi! I saw that there were no accepted pull requests to this issue, so I decided to take a stab at it to make it a little clearer in the history panel. I hope this works!

2021-12-02 13:59 UTC, tyrasd commented
this is for issue #8784

2021-12-02 14:06 UTC, tyrasd requested changes
Can you please also change the label of the changeset link to osm as well (currently line 79)?

I'm wondering if we should make these texts translatable. I think it would not hurt. I can change that for you if you're not feeling comfortable, but it would need additional entries in [`data/core.yaml`](https://github.com/openstreetmap/iD/blob/develop/data/core.yaml) and the translated text needs to be appended here using `.call(t.append(…))` instead of `.text(…)`. See line 24 for an example.

2021-12-05 00:58 UTC, jasonghent98 commented
Hi,
Let me know if that looks better. In regards to making the texts translatable, are you referring to the core.yaml file itself, or rather the texts within the OSM history panel links (history, profile, changeset)? If the first, I could probably just use a third-party tool like iCanLocalize to do that. If the latter, I can also take care of that within the yaml file.

2021-12-06 07:53 UTC, 1ec5 commented on modules/ui/panels/history.js
> +                .text('OSM Profile');
Also call `t.append` here. The argument to `t.append` should refer to an entry in English that you’ll need to add to in data/core.yaml. Once this PR lands, translators will be able to provide translations using Transifex, so there’s no need to handle the translations yourself.

2021-12-06 17:14 UTC, tyrasd commented
> In regards to making the texts translatable, are you referring to the core.yaml file itself, or rather the texts within the OSM history panel links (history, profile, changeset)?

I was referring to the texts of the links in the history panel. I've just written a small tutorial about how to do that here: https://github.com/openstreetmap/iD/wiki/How-to-use-iD%27s-localizer-module

2021-12-06 17:43 UTC, jasonghent98 commented
Thanks for the clarification. Let me know how this looks.

2021-12-06 17:55 UTC, tyrasd requested changes
Looks like it's almost done! Only two more things:

1. drop the `.text('…')` lines (lines 44, 81 and 204). The text adding is done already with the `.call(t.append(…));`
2. start all new strings in capital letters perhaps?

2021-12-07 11:43 UTC, tyrasd approved these changes

2021-12-07 11:45 UTC, merged