Remove accidental mismatch of "PAMAP"
openstreetmap/iD pull request #8889
Opened 2022-01-09 17:37 UTC by cicku

![image](https://user-images.githubusercontent.com/686438/148693757-2ad7fddc-7b2f-4aa3-99d0-cc9a774c5a07.png)

2022-01-09 22:12 UTC, mmd-osm commented
https://www.openstreetmap.org/way/166528135 would no longer be flagged by this change, although it's still incompatible data.
Adding more tests in https://github.com/openstreetmap/iD/blob/develop/test/spec/validations/incompatible_source.js might be good.

2022-01-10 00:29 UTC, cicku commented
I don’t know anything about Europe so I can’t help here. As far as I can see it’s a regression introduced by a patch to warn about proprietary Chinese data.

2022-01-28 11:12 UTC, tyrasd requested changes

2022-01-28 11:12 UTC, tyrasd commented on modules/validations/incompatible_source.js
> +      regex: /(^amap$|amap\.at|^amap\.com|autonavi|mapabc|高德)/i
Can you please drop `amap.at` from this list? It doesn't have anything to do with the data from [AutoNavi](https://en.wikipedia.org/wiki/AutoNavi), which this rule is obviously about. The amap.at domain is owned by an Austrian government agency.

@mmd-osm if you'd like to see this URL added to the list of incompatible sources, please open a new PR (or issue) for it. :blush: At first glance, amap.at seems to be a former, now dysfunctional, URL of what is now available at http://www.austrianmap.at/amap/, which AFAICS does contain non-open data (e.g., `ÖK 50`).

2022-01-28 14:06 UTC, cicku commented on modules/validations/incompatible_source.js
> +      regex: /(^amap$|amap\.at|^amap\.com|autonavi|mapabc|高德)/i
Done

2022-01-28 14:34 UTC, tyrasd approved these changes

2022-01-28 14:34 UTC, merged