FIX: issue-8750
openstreetmap/iD pull request #8978
Opened 2022-02-10 22:53 UTC by Pho3b

After studying the ID software architecture for a bit i came up with this solution for the `issue-8750`.

I performed various test on my local machine and it seems to cover the cases described in the issue.
Unit tests were started, and no errors were found.

Hope it can be helpful, i will be available for any further updates.

2022-02-11 06:26 UTC, tordans commented
Ping https://github.com/openstreetmap/iD/issues/8750

2022-02-15 13:38 UTC, tyrasd requested changes
Hey. Thanks for the pull request. 

While testing it, I noticed some strange behavior: when following another way which ends in a T-junction, the appended way jumps back to the first contact with the followed way and repeats in a circle infinitely. I think this is a bug, isn't it?


![ezgif-7-90d000d839](https://user-images.githubusercontent.com/1927298/154072400-94306d9d-e9bd-4b85-9257-c1fb4b890cbc.gif)

Can you please explain in more detail how you think the follow operation should work in situations like this (and in general). Thanks!

2022-02-17 20:22 UTC, Pho3b commented
hey @tyrasd thank you very much for the code review.

I executed some test and, correct me if i am wrong, it seems to me that i could reproduce the behavior you reported even without my code changes. 
What i noticed is that now, not stopping when a node that has multiple parent is encountered, lets that behavior to show up more often.

That said, i just pushed a new commit that ends the following action if a node that has already been followed is encountered again, this should avoid the user to end up following infinite circles.

I hope i correctly answered your question, waiting for your feedback.
Thanks!

2022-05-15 17:31 UTC, Pho3b commented
Hey guys, any news on this ? 
If there's there something i can do to improve/speed up the review let me know !

Thanks

2022-05-20 15:38 UTC, tyrasd commented
Sorry, I haven't had time to give it a deeper look yet. I'll try to come around it next week. :)

2022-10-22 08:23 UTC, Pho3b commented
Hi, any updates regarding this PR ?

Thank you

2024-08-23 07:26 UTC, DujaOSM commented
I objected on implementing this in #8750, since it would hamper usability in a significant number of use cases.

2026-06-23 10:44 UTC, tyrasd commented
Closing in favour of #9340. (also: Mixing keyboard and mouse hover at the same time seems also a bit counter-intuitive from a usability point of view.)

Thanks for your effort anyway! :bow:

2026-06-23 10:44 UTC, closed without merging