Change None background to white, change color of roads
openstreetmap/iD pull request #9307
Opened 2022-09-27 01:09 UTC by anniemichel

Address Issue #9281 

Changes:
- Changed default map background to white
- Also changed residential and service roads to light grey, and driveways to a darker yellow. 

Purpose:
To improve readability and UX

Visuals:
Before:
<img width="1440" alt="Screen Shot 2022-09-26 at 3 51 43 PM" src="https://user-images.githubusercontent.com/80357302/192367215-a00ce611-15ef-4654-b7b8-dfed38616ea9.png">
After:
<img width="1440" alt="Screen Shot 2022-09-26 at 3 45 36 PM" src="https://user-images.githubusercontent.com/80357302/192366144-128872c4-3975-45ce-82a2-7f84af3905a9.png">

2022-09-27 12:16 UTC, tyrasd commented
Thanks for your effort. However, I think this needs a bit more thought (and work) to be useful. There are more features currently rendered as white lines or areas (e.g. the areas of hospitals or man made structures) which would have low contrast against the white background. Similarly, newly created and still untagged lines are rendered white and thus would be invisible on the white background. Further, the background of the context (right click) menu is also white, which is poorly visible against a white background.

2022-09-29 05:07 UTC, mxdanger commented
I'd argue that getting flash banged does not improve readability and UX. But on a more serious note, most of the styling is made for aerial imagery, which is usually a darker color. That means using a white background actually decreases readability and UX due to less contrast, along with other issues that @tyrasd mentioned.

2023-09-24 21:14 UTC, pnorman requested changes
Could you add a preview of how this looks against a typical aerial image, which is normally darker?

Of particular concern is using grey for roads, because roads are often grey on the imagery. How does this work?

2026-02-03 09:17 UTC, tyrasd commented
closing as stale

2026-02-03 09:17 UTC, closed without merging